import { GlobalStateProvider } from '@/state'
import './globals.css'
import type { Metadata } from 'next'
import { TrpcProvider } from '@/utils/trpc/trpc-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>
          <GlobalStateProvider>{children}</GlobalStateProvider>
        </TrpcProvider>
      </body>
    </html>
  )
}

export default RootLayout
