import { GlobalStateProvider } from '@/state'
import type { Metadata } from 'next'
import { TrpcProvider } from '@/utils/trpc/trpc-provider'
import { GlobalStyles } from './globalStyles'
import StyledComponentsRegistry from '@/lib/registry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="en">
        <body>
          <TrpcProvider>
            <StyledComponentsRegistry>
              <GlobalStyles />
              <GlobalStateProvider>{children}</GlobalStateProvider>
            </StyledComponentsRegistry>
          </TrpcProvider>
        </body>
      </html>
    </>
  )
}

export default RootLayout
